name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt update && sudo apt install openssh-client -y

      - name: Deploy to server
        run: |
          ssh root@206.189.125.143 'cd projet-12-katsumeme-back/ && git pull'
