name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Les étapes suivantes se déroulent à partir de la racine du dépôt cloné
      - name: Install dependencies
        run: npm install

      - name: Generate Prisma client
        run: npm run prisma:generate

      - name: Deploy Prisma changes
        run: npm run prisma:deploy

      - name: Restart PM2 process
        run: pm2 restart katsumeme_prod
