name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into DigitalOcean Droplet and pull changes
        uses: appleboy/ssh-action@master
        with:
          host: 206.189.125.143
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd projet-12-katsumeme-back/
            git pull origin main

