name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 22.x
      uses: actions/setup-node@v2
      with:
        node-version: '22.0.0'

    - name: SSH into Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd katsumeme-back-sam
          git pull
          npm install
          npm run prisma:generate
          npm run prisma:deploy
          pm2 restart 1
          pm2 save
