name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into DigitalOcean Droplet and pull changes
        uses: appleboy/ssh-action@master
        with:
          host: 206.189.125.143
          username: root
          key: |
            -----BEGIN RSA PRIVATE KEY-----
              b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
              NhAAAAAwEAAQAAAgEAp/OfHsF/QSC9IuEqZDLu2csu3faq6ifZMlQR+F4Emf6XIcExMVsT
              FxSm+uSmyM2iBdfxDsilqoUi4XPWNck7nLjbsNqE6W2+9OBnSYhWCpMojLVbvwoQQSBiet
              F1+yF+VGp/Una7AnZxTXP5dYZh43ddwV7BjBtGkL/tIj6DmKRiLyVD4odUvQSSKtB+b2rn
              0y2cbcHM/LKG9vfhXpwG24tCvVjYduWCki3J5yTGCXbnmRC4jdWCLOvMQ+L3QCg5hG3306
              RHCKarzFRWChccvRh2OFj5GLo9TCJpoj4xr/eoQKpugOvSRBSPNd9izmXvyWtxgtqhndN2
              Ti9OXCg4QidRU/k/BW84HFp/8xx3EB53IhCA1ZpjsKoVBopF053ZtJ5sEEaM2P225lQKy6
              5TUpFufC8KNF6ju7ad0p3zsfG+tXxZGin/SVMqngpzds8YxJnco4fSa7gGcK5EF/FI5GlB
              JgyLHnKoa3SzNQjgpCOJSzrrDp0i1jGK6enJgzDaUmVEPiMC8YkklzFMk/Uch4AyLvZPJG
              gnx9ivlt/DjHWoDr5wzHxj90eQlnp6mbJkY1/mYe32itVr/ydVpwZRK8jM5r+2RI5tdTHY
              lFKLw80dnOHZL6lgHAnZgCLR7Mg9FlKHWEuTPLGXgzY4MZZCbmt7oUuPmcLeVmU7dZosvf
              kAAAdQHbUIPR21CD0AAAAHc3NoLXJzYQAAAgEAp/OfHsF/QSC9IuEqZDLu2csu3faq6ifZ
              MlQR+F4Emf6XIcExMVsTFxSm+uSmyM2iBdfxDsilqoUi4XPWNck7nLjbsNqE6W2+9OBnSY
              hWCpMojLVbvwoQQSBietF1+yF+VGp/Una7AnZxTXP5dYZh43ddwV7BjBtGkL/tIj6DmKRi
              LyVD4odUvQSSKtB+b2rn0y2cbcHM/LKG9vfhXpwG24tCvVjYduWCki3J5yTGCXbnmRC4jd
              WCLOvMQ+L3QCg5hG3306RHCKarzFRWChccvRh2OFj5GLo9TCJpoj4xr/eoQKpugOvSRBSP
              Nd9izmXvyWtxgtqhndN2Ti9OXCg4QidRU/k/BW84HFp/8xx3EB53IhCA1ZpjsKoVBopF05
              3ZtJ5sEEaM2P225lQKy65TUpFufC8KNF6ju7ad0p3zsfG+tXxZGin/SVMqngpzds8YxJnc
              o4fSa7gGcK5EF/FI5GlBJgyLHnKoa3SzNQjgpCOJSzrrDp0i1jGK6enJgzDaUmVEPiMC8Y
              kklzFMk/Uch4AyLvZPJGgnx9ivlt/DjHWoDr5wzHxj90eQlnp6mbJkY1/mYe32itVr/ydV
              pwZRK8jM5r+2RI5tdTHYlFKLw80dnOHZL6lgHAnZgCLR7Mg9FlKHWEuTPLGXgzY4MZZCbm
              t7oUuPmcLeVmU7dZosvfkAAAADAQABAAACABONGI5C4fKV0jKt4cqPg87KeHKaGQggWqhB
              UWS3ZCN9l8AUDmsTki+3BZ+yD6jTSEvUGSGaka99p2N1ob955SS/v8JRE9UdI5Q7zcZJdt
              OtERS9NXiSHjWIpLItsUVqXxuKWLdDr04wdczZhfYMjldlkT5WDqOl1rN5xiv8+UKDC1N3
              6/TCQobs8euGQRutBx7mIb5Ep91YVn4IOd3yvZkf12V1ouBHZClqZ2UvGpcmNnxy7fsD2m
              8qhWk3Mgdvz09HYmjKqEK9bUUgYbIzwdKQ9w0k7V13q7RR0rhyc0QL6VQayvmayivG9Wtk
              7Wp/wxfQWELOeu8lm1FrcByqCW9YhClLxIiJ55/J/kog/sCWdrc+pRZx2C+j9qMgWv8r/D
              eZOwVSARjvdJGZaJqnwMX98kK3/foJCqEy8tSJcbinVst0RKaR0jPeUVlijgtTj05Ca/ES
              PaaviIfFs6iQmR3gslRWp0xQVo2GALxr5vCHp9mUvSCPS69ege2vGWPmA0yuErzq3jrCNM
              lpm3vZm70rZiWzqcBf9V4BneMstkCrJqqLc93SKIM6GhNfLzbMqd1wkPEY/wPdtPq5rY7W
              XKjKl4+3Rl5pq9rIrjJlT+iZcEMW8s19T5XKXg0jeaD/OeQYbKmvMz/5UKJfF+jLk//uoy
              H7A4xpYxXhJZIRPV6xAAABAEA9fS2TbZIQwqoZ4hzwrZAn6s1kh2oOptWuz4ibpQwz8c/s
              FaG7FJ5PxH45c0qEUSWnpHZof0FqxxWIhApKhWjg7kRnxy0pgPF63YmwncLv0Zx+j8qtjA
              AMEqS647yV65oAGsx6L46ovHX8mCtuwTQ5LmyikipIhEy6agN+sLSF9+Qpod08/0lGpt1e
              +6txXDg+0b5Byu8BdXu0kwKqLxBXDFSn41in01vJXm4LwEWdQMZ+6kBUFMV7mmKOStdeV9
              nmwDWsBYgsZZ4Yobk3b3svgRajM4C0V31xCngnfit8IdHIRI2GxGs1MoQaTl5O5sqvQMS0
              a1qPOIgALdnaC/cAAAEBAOTAIM5YKf+A1D2cX2/i6sAJWONRA+viBBQJ9AwiYsyFva04xt
              xp14uv0LnFO2dQDsgF1cv7j+YL4vXOj/PnjmNFkHlVDuvTPLDT6VzmClnrMZE75oolMNSS
              MDOQi5Cayf7g4yiB+lm1JiKun93mV/MhC3CAla3wQh//iUhtQL5qc9dnLSYsAKuW75Akr4
              ctFB4QuUOXHj+4S2r81rrci4iturpNb4N9UbR5RyLGE3F14OBcCzL2xkKFQOwn3rDtqLXA
              ZF4RZwtJgaDbhCXxQnN6ygACJwXlhaiqdpD/D2cKqrGjfOudiVTkYJBuwl1FX0B55tPvBz
              2AkPROKeeioLEAAAEBALv1Zihg1YqDVdVJey1oKhOAZeTxZxHBZqaz4zV7cY53y4Xhm0Oo
              21mBu4cLwfg8JVtliDl7zm10niiCEPJTcPi1NSqszgRzkz76NyqXZ//uJdCr3LdAtIraBR
              65OiHzPbwhq6XU4zrZoWuYaQmgy2MIurf9t45RiDicJy2PyMcQ5XMtT4xtdF0Z1WcmaK1r
              arRefFPYmeEnvbpwdtjSVl2gGmfTk1TfxY/TdQiacrQFnRBg+Mfwe9SUPZC08JtvqZIwCd
              814dXc4uaPaMTm+0NIxJa827ZScFzaG6A37UTYoa8zhdAHg0h6ln6zsKGeG+1XiNeNqo/A
              eXwAgNfig8kAAAAUc2FteWVsMjA5QGhvdG1haWwuZnIBAgMEBQYH
            -----END RSA PRIVATE KEY-----
          script: |
            cd projet-12-katsumeme-back/
            git pull origin main

