name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into DigitalOcean Droplet and pull changes
        uses: appleboy/ssh-action@master
        with:
          host: 206.189.125.143
          username: root
          key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEAp/OfHsF/QSC9IuEqZDLu2csu3faq6ifZMlQR+F4Emf6XIcEx
            MVsTFxSm+uSmyM2iBdfxDsilqoUi4XPWNck7nLjbsNqE6W2+9OBnSYhWCpMojLVb
            vwoQQSBietF1+yF+VGp/Una7AnZxTXP5dYZh43ddwV7BjBtGkL/tIj6DmKRiLyVD
            4odUvQSSKtB+b2rn0y2cbcHM/LKG9vfhXpwG24tCvVjYduWCki3J5yTGCXbnmRC4
            jdWCLOvMQ+L3QCg5hG3306RHCKarzFRWChccvRh2OFj5GLo9TCJpoj4xr/eoQKpu
            gOvSRBSPNd9izmXvyWtxgtqhndN2Ti9OXCg4QidRU/k/BW84HFp/8xx3EB53IhCA
            1ZpjsKoVBopF053ZtJ5sEEaM2P225lQKy65TUpFufC8KNF6ju7ad0p3zsfG+tXxZ
            Gin/SVMqngpzds8YxJnco4fSa7gGcK5EF/FI5GlBJgyLHnKoa3SzNQjgpCOJSzrr
            Dp0i1jGK6enJgzDaUmVEPiMC8YkklzFMk/Uch4AyLvZPJGgnx9ivlt/DjHWoDr5w
            zHxj90eQlnp6mbJkY1/mYe32itVr/ydVpwZRK8jM5r+2RI5tdTHYlFKLw80dnOHZ
            L6lgHAnZgCLR7Mg9FlKHWEuTPLGXgzY4MZZCbmt7oUuPmcLeVmU7dZosvfkCAwEA
            AQKCAgATjRiOQuHyldIyreHKj4POynhymhkIIFqoQVFkt2QjfZfAFA5rE5IvtwWf
            sg+o00hL1BkhmpGvfadjdaG/eeUkv7/CURPVHSOUO83GSXbTrREUvTV4kh41iKSy
            LbFFal8bili3Q69OMHXM2YX2DI5XZZE+Vg6jpdazecYr/PlCgwtTd+v0wkKG7PHr
            hkEbrQce5iG+RKfdWFZ+CDnd8r2ZH9dldaLgR2QpamdlLxqXJjZ8cu37A9pvKoVp
            NzIHb89PR2JoyqhCvW1FIGGyM8HSkPcNJO1dd6u0UdK4cnNEC+lUGsr5msorxvVr
            ZO1qf8MX0FhCznrvJZtRa3AcqglvWIQpS8SIieefyf5KIP7Alna3PqUWcdgvo/aj
            IFr/K/w3mTsFUgEY73SRmWiap8DF/fJCt/36CQqhMvLUiXG4p1bLdESmkdIz3lFZ
            Yo4LU49OQmvxEj2mr4iHxbOokJkd4LJUVqdMUFaNhgC8a+bwh6fZlL0gj0uvXoHt
            rxlj5gNMrhK86t46wjTJaZt72Zu9K2Yls6nAX/VeAZ3jLLZAqyaqi3Pd0iiDOhoT
            Xy82zKndcJDxGP8D3bT6ua2O1lyoypePt0ZeaavayK4yZU/omXBDFvLNfU+Vyl4N
            I3mg/znkGGyprzM/+VCiXxfoy5P/7qMh+wOMaWMV4SWSET1esQKCAQEA5MAgzlgp
            /4DUPZxfb+LqwAlY41ED6+IEFAn0DCJizIW9rTjG3GnXi6/QucU7Z1AOyAXVy/uP
            5gvi9c6P8+eOY0WQeVUO69M8sNPpXOYKWesxkTvmiiUw1JIwM5CLkJrJ/uDjKIH6
            WbUmIq6f3eZX8yELcICVrfBCH/+JSG1Avmpz12ctJiwAq5bvkCSvhy0UHhC5Q5ce
            P7hLavzWutyLiK26uk1vg31RtHlHIsYTcXXg4FwLMvbGQoVA7CfesO2otcBkXhFn
            C0mBoNuEJfFCc3rKAAInBeWFqKp2kP8PZwqqsaN8652JVORgkG7CXUVfQHnm0+8H
            PYCQ9E4p56KgsQKCAQEAu/VmKGDVioNV1Ul7LWgqE4Bl5PFnEcFmprPjNXtxjnfL
            heGbQ6jbWYG7hwvB+DwlW2WIOXvObXSeKIIQ8lNw+LU1KqzOBHOTPvo3Kpdn/+4l
            0Kvct0C0itoFHrk6IfM9vCGrpdTjOtmha5hpCaDLYwi6t/23jlGIOJwnLY/IxxDl
            cy1PjG10XRnVZyZorWtqtF58U9iZ4Se9unB22NJWXaAaZ9OTVN/Fj9N1CJpytAWd
            EGD4x/B71JQ9kLTwm2+pkjAJ3zXh1dzi5o9oxOb7Q0jElrzbtlJwXNoboDftRNih
            rzOF0AeDSHqWfrOwoZ4b7VeI142qj8B5fACA1+KDyQKCAQEAq49tC1UUKox0ocCl
            00Rcy6o3AEXCqybX6C+O2YrwjnO/zirG+ohnIFy8Lpe99b4VV+8IafRB+Ebx8Wj6
            jfMc11dVA6rHhhbnbbeBTis5mDbM9h/2x6Uc+lCp1gKSqeFtnbsMo1TYbm9uKpTN
            UZ9wVuhxq+7EU6/d6CG+1JMb+7PbLbI0KmzWE9sf0Puyqa8lZ2cji43LIf8WkScP
            5RWDkP67DP8Go5dZsAFFWM81xeKixaJCw/ZQu5M1HejJG+kiny2sGOD0Z4K5tert
            MYfATtvIpDj5C3MYy2cNhbHF24IkgxYampuMZB7kTW7EVy+wQKssc8bRp07FaHU2
            +IMAAQKCAQA8f/31C05Q+ntbXv6mG/xHMLIbolSB05XeHNMKuQRRTmAVZQwcGDMa
            uXaKPo+d/oYryB+0GRTWCI6MDWm1BoS7mWBWry7VIfqIb/Pn4rpYF+jWJSuzVMGI
            XCr/u7FpkikR8GiWxVKq87hQsMtGjRpKc1netW0rAzVsu16k/L4szVR94VzUn7qv
            6QvW2vcgsw2ypyMvve2yGp+obmDi47lnA4zcVK78x9aIuBDYxxYauh/XUM9jVBYX
            0+uJM6Sq86NKaeoTjf12YFYszoZzssG346lbt8ilBB4k1RPFW5sk6PIKOfRdhL2O
            S987Q02ciA8HM4DZmUEIanTwJB1U4BV5AoIBAEA9fS2TbZIQwqoZ4hzwrZAn6s1k
            h2oOptWuz4ibpQwz8c/sFaG7FJ5PxH45c0qEUSWnpHZof0FqxxWIhApKhWjg7kRn
            xy0pgPF63YmwncLv0Zx+j8qtjAAMEqS647yV65oAGsx6L46ovHX8mCtuwTQ5Lmyi
            kipIhEy6agN+sLSF9+Qpod08/0lGpt1e+6txXDg+0b5Byu8BdXu0kwKqLxBXDFSn
            41in01vJXm4LwEWdQMZ+6kBUFMV7mmKOStdeV9nmwDWsBYgsZZ4Yobk3b3svgRaj
            M4C0V31xCngnfit8IdHIRI2GxGs1MoQaTl5O5sqvQMS0a1qPOIgALdnaC/c=
            -----END RSA PRIVATE KEY-----
          script: |
            cd projet-12-katsumeme-back/
            git pull origin main

